complete -c systemd-boot-friend -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "init" -d 'Initialize systemd-boot and install the newest kernel'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "list" -d 'List available kernels'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "install-kernel" -d 'Install specific version of kernel'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install-kernel" -s h -l help -d 'Prints help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install-kernel" -s V -l version -d 'Prints version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
